In [ ]:
# menggunakan numpy, pytoch dan tensorflow buatlah matrix ukuran 3x3 lalu hitung nilai frobenius norm

# Using numpy

In [42]:
import numpy as np

In [43]:
X = np.array([[6, 2, 1], [2, 5, 1], [6, 6, 1]])
X

array([[6, 2, 1],
       [2, 5, 1],
       [6, 6, 1]])

In [ ]:
X = np.array([[1, 2], [3, 4]])
X

In [14]:
(6**2 + 2**2 + 6**2 + 2**2 + 5**2 + 6**2 + 1**2 + 1**2 + 1**2)**(1/2)

12.0

In [15]:
np.linalg.norm(X) # same function as for vector L2 norm

np.float64(12.0)

# Using pytoch

In [16]:
import torch

In [18]:
X_pt = torch.tensor([[6, 2, 1], [2, 5, 1], [6, 6, 1]]) # torch.norm() supports floats only
X_pt

tensor([[6, 2, 1],
        [2, 5, 1],
        [6, 6, 1]])

In [25]:
torch.norm(X_pt.float())

tensor(12.)

# Using TensorFlow

In [35]:
import tensorflow as tf


In [40]:
X_tf = tf.Variable([[6, 2, 1], [2, 5, 1], [6, 6, 1]], dtype=tf.float32)
X_tf


<tf.Variable 'Variable:0' shape=(3, 3) dtype=float32, numpy=
array([[6., 2., 1.],
       [2., 5., 1.],
       [6., 6., 1.]], dtype=float32)>

In [41]:
tf.norm(X_tf)

<tf.Tensor: shape=(), dtype=float32, numpy=12.0>