In [ ]:
# buatlah matriks simetris dengan ukuran 3x3 dan buktikan bahwa itu merupakan matriks simetris

In [1]:
import numpy as np

In [6]:
X_sym = np.array([[2, 5, 0], [5, 1, 6], [0, 6, 2]])
X_sym

array([[2, 5, 0],
       [5, 1, 6],
       [0, 6, 2]])

In [7]:
X_sym.T

array([[2, 5, 0],
       [5, 1, 6],
       [0, 6, 2]])

In [8]:
X_sym.T == X_sym

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

# matriks identitas

In [ ]:
# menggunakan pytorch, buatlah matriks identitas I dengan ukuran 4x4

In [9]:
import torch

In [11]:
I = torch.tensor([[1, 0, 0, 0], [0, 1, 0, 0], [0, 0, 1, 0], [0, 0, 0, 1]])
I

tensor([[1, 0, 0, 0],
        [0, 1, 0, 0],
        [0, 0, 1, 0],
        [0, 0, 0, 1]])

In [13]:
# menggunakan pytorch, buatlah vector b_pt dengan ukuran 4x1
x_pt = torch.tensor([[25], [15], [61], [62]])
x_pt

tensor([[25],
        [15],
        [61],
        [62]])

In [14]:
# kalikan matrix I dengan vector b_pt
torch.matmul(I, x_pt)

tensor([[25],
        [15],
        [61],
        [62]])