In [1]:
import numpy as np

In [3]:
# buat matrix X berukuran 2x3 menggunakan numpy
X = np.array([[62, 26, 15], [61, 15, 25]])
X

array([[62, 26, 15],
       [61, 15, 25]])

In [4]:
# tampilkan ukuran dari matrix X
print("shape:", X.shape)

shape: (2, 3)


In [5]:
# tampilkan ukuran dari matrix X
print("size:", X.size)

size: 6


In [6]:
# tampilkan seluruh elemen dari kolom pertama dari matrix X
print("kolom pertama:", X[:,0])

kolom pertama: [62 61]


In [7]:
# tampilkan seluruh elemen dari baris kedua dari matrix X
print("baris kedua:", X[1,:])

baris kedua: [61 15 25]


In [8]:
#ulangi soal nomor 1 menggunakan pytorch
import torch

In [11]:
X_pt = torch.tensor([[62, 26, 15], [61, 15, 25]])
X_pt

tensor([[62, 26, 15],
        [61, 15, 25]])

In [12]:
X_pt.shape # pythonic relative to TensorFlow

torch.Size([2, 3])

In [13]:
torch.Size([2, 3])

torch.Size([2, 3])

In [14]:
X_pt[1,:] # N.B.: Python is zero-indexed; written algebra is one-indexed

tensor([61, 15, 25])

In [15]:
#ulangi soal nomor 1 menggunakan tensorflow
import tensorflow as tf

In [16]:
X_tf = tf.Variable([[62, 26, 15], [61, 15, 25]])
X_tf

<tf.Variable 'Variable:0' shape=(2, 3) dtype=int32, numpy=
array([[62, 26, 15],
       [61, 15, 25]], dtype=int32)>

In [17]:
tf.rank(X_tf)

<tf.Tensor: shape=(), dtype=int32, numpy=2>

In [18]:
tf.shape(X_tf)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([2, 3], dtype=int32)>

In [19]:
X_tf[1,:]

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([61, 15, 25], dtype=int32)>