In [23]:
# 1. buat matrix X dengan ukuran 2x3 menggunakan numpy
import numpy as np
import torch
import tensorflow as tf

In [24]:
x = np.array([[23, 13], [17, 24], [67, 11]])
x

array([[23, 13],
       [17, 24],
       [67, 11]])

In [25]:
# buat matrix X_pt dengan ukuran 2x3 menggunakan pytorch
x_pt = torch.tensor([[23, 13], [17, 24], [67, 11]])
x_pt

tensor([[23, 13],
        [17, 24],
        [67, 11]])

In [26]:
# buat matrix X_tf dengan ukuran 2x3 menggunakan tensorflow
x_tf = tf.Variable([[23, 13], [17, 24], [67, 11]])
x_tf

<tf.Variable 'Variable:0' shape=(3, 2) dtype=int32, numpy=
array([[23, 13],
       [17, 24],
       [67, 11]], dtype=int32)>

In [27]:
# 2. lakukan transpose pada matrix X, X_pt dan X_tf

Numpy

In [28]:
x.T

array([[23, 17, 67],
       [13, 24, 11]])

Torch

In [29]:
x_pt.T

tensor([[23, 17, 67],
        [13, 24, 11]])

TensorFlow

In [30]:
tf.transpose(x_tf)

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[23, 17, 67],
       [13, 24, 11]], dtype=int32)>