In [ ]:
#buat matrix X dengan ukuran 2x3 menggunakan numpy
import numpy as np

In [ ]:
X = np.array([[25, 15, 61], [12, 4, 7]])
print("X=", X)

X= [[25 15 61]
 [12  4  7]]


In [ ]:
#hitung berapa hasil penjumlahan elemen matrix X dengan fungsi sum
X.sum()
print("hasil penjumlahan elemen matrix X:", X.sum())

hasil penjumlahan elemen matrix X: 124


In [ ]:
#buat matrix X_tf dengan ukuran 2x3 menggunakan tensorflow
import tensorflow as tf

In [ ]:
X_tf = tf.Variable([[25, 15, 61], [12, 4, 7]])
print("X=", X_tf)

X= <tf.Variable 'Variable:0' shape=(2, 3) dtype=int32, numpy=
array([[25, 15, 61],
       [12,  4,  7]], dtype=int32)>


In [ ]:
#hitung hasil penjumlahan seluruh elemen matrix X_pt
tf.reduce_sum(X_tf)
print("hasil penjumlahan elemen matrix X:", tf.reduce_sum(X_tf))

hasil penjumlahan elemen matrix X: tf.Tensor(124, shape=(), dtype=int32)


In [ ]:
##buat matrix X_pt dengan ukuran 2x3 menggunakan pytorch
import torch

In [ ]:
X_pt = torch.tensor([[25, 15, 61], [12, 4, 7]])
print("X=", X_pt)

X= tensor([[25, 15, 61],
        [12,  4,  7]])


In [ ]:
torch.sum(X_pt)
print("hasil penjumlahan elemen matrix X:", torch.sum(X_pt))

hasil penjumlahan elemen matrix X: tensor(124)


In [ ]:
#hitung hasil penjumlahan matrix X, X_pt, X_tf berdasarkan row nya
X.sum(axis=1)
print("hasil penjumlahan matrix X berdasarkan rownya:", X.sum(axis=1))

hasil penjumlahan matrix X berdasarkan rownya: [101  23]


In [ ]:
torch.sum(X_pt, 1)
print("hasil penjumlahan matrix X berdasarkan rownya:", torch.sum(X_pt, 1))

hasil penjumlahan matrix X berdasarkan rownya: tensor([101,  23])


In [ ]:
tf.reduce_sum(X_tf, axis=1)
print("hasil penjumlahan matrix X berdasarkan rownya:", tf.reduce_sum(X_tf, axis=1))

hasil penjumlahan matrix X berdasarkan rownya: tf.Tensor([101  23], shape=(2,), dtype=int32)


In [ ]:
#hitung hasil penjumlahan matrix X, X_pt, X_tf berdasarkan kolom nya
X.sum(axis=0)
print("hasil penjumlahan matrix X berdasarkan rownya:", X.sum(axis=0))

hasil penjumlahan matrix X berdasarkan rownya: [37 19 68]


In [ ]:
torch.sum(X_pt, 0)
print("hasil penjumlahan matrix X berdasarkan rownya:", torch.sum(X_pt, 0))

hasil penjumlahan matrix X berdasarkan rownya: tensor([37, 19, 68])


In [ ]:
tf.reduce_sum(X_tf, axis=0)
print("hasil penjumlahan matrix X berdasarkan rownya:", tf.reduce_sum(X_tf, axis=0))

hasil penjumlahan matrix X berdasarkan rownya: tf.Tensor([37 19 68], shape=(3,), dtype=int32)


In [ ]:
#hitung nilai minimal dari matrix X, X_pt dan X_tf
X.min()
print("nilai minimal dari matrix X adalah:", X.min())

nilai minimal dari matrix X adalah: 4


In [ ]:
torch.min(X_pt)
print("nilai minimal dari matrix X adalah:", torch.min(X_pt))

nilai minimal dari matrix X adalah: tensor(4)


In [ ]:
tf.reduce_min(X_tf)
print("nilai minimal dari matrix X adalah:", tf.reduce_min(X_tf))

nilai minimal dari matrix X adalah: tf.Tensor(4, shape=(), dtype=int32)


In [ ]:
#hitung nilai maksimal dari matrix X, X_pt dan X_tf
X.max()
print("nilai maksimal dari matrix X adalah:", X.max())

nilai maksimal dari matrix X adalah: 61


In [ ]:
torch.max(X_pt)
print("nilai maksimal dari matrix X adalah:", torch.max(X_pt))

nilai maksimal dari matrix X adalah: tensor(61)


In [ ]:
tf.reduce_max(X_tf)
print("nilai maksimal dari matrix X adalah:", tf.reduce_max(X_tf))

nilai maksimal dari matrix X adalah: tf.Tensor(61, shape=(), dtype=int32)


In [ ]:
#hitung nilai rata-rata dari matrix X, X_pt, dan X_tf
np.mean(X)
print("nilai rata-rata dari matrix X adalah:", np.mean(X))

nilai rata-rata dari matrix X adalah: 20.666666666666668


In [ ]:
torch.mean(X_pt.float())
print("nilai rata-rata dari matrix X adalah:", torch.mean(X_pt.float()))

nilai rata-rata dari matrix X adalah: tensor(20.6667)


In [ ]:
tf.reduce_mean(X_tf)
print("nilai rata-rata dari matrix X adalah:", tf.reduce_mean(X_tf))

nilai rata-rata dari matrix X adalah: tf.Tensor(20, shape=(), dtype=int32)


In [ ]:
#hitung hasil perkalian seluruh elemen matrix X, X_pt, dan x_tf
X.prod()
print("hasil perkalian seluruh elemen matrix X adalah:", X.prod())

hasil perkalian seluruh elemen matrix X adalah: 7686000


In [ ]:
torch.prod(X_pt)
print("hasil perkalian seluruh elemen matrix X adalah:",torch.prod(X_pt))

hasil perkalian seluruh elemen matrix X adalah: tensor(7686000)


In [ ]:
tf.reduce_prod(X_tf)
print("hasil perkalian seluruh elemen matrix X adalah:", tf.reduce_prod(X_tf))

hasil perkalian seluruh elemen matrix X adalah: tf.Tensor(7686000, shape=(), dtype=int32)
